FABRIC 					:= m2

EXTRA_FABRIC_RTL_DEPS 	:= prga_fifo_resizer.v
EXTRA_FABRIC_RTL_DEPS 	+= prga_fifo.v
EXTRA_FABRIC_RTL_DEPS 	+= prga_ram_1r1w.v
EXTRA_FABRIC_RTL_DEPS 	+= prga_fifo_lookahead_buffer.v

include ../Makefile.inc
